### ISSUE TITLE
Big "THANK YOU" to developers

### ISSUE THREAD

**Issue by mercmobily** [Polymer/lit-element#1011] opened 2020-06-02 00:53 UTC
This is not really an issue.

I just want to take the time to say "THANK YOU" (yes, in capital letters) to lit-element and lit-html's developers. A special mention goes to @justinfagnani 
Every time I trace the code for debugging, I discover something awesome lit-html or lot-element does. My applications are immensely fast. And the level of support they all provide is incredible. You can see it in these very issues.

This is free/open source software at its best.

The internet world would be a much sadder place without these technologies.

"THANK YOU".

**Comment by vdegenne** [comment] 2020-06-02 14:54
I've always wanted to thank the team like that but I thought it was not appropriate to post  here. But now that someone did I hop in the train and add my "THANK YOU" too 🤩👍

Polymer has really made my life easier. The web is always evolving but Polymer is what really helped me to kickstart many of my projects.

Thanks to everyone

**Comment by justinfagnani** [comment] 2020-06-04 18:36
Closing this issue as unable to reproduce 🤪

j/k thank you so much for the encouragement, we really, really appreciate it! We're very glad that our choices have ended up working out so well for developers, and we love our community!

**Comment by sorvell** [comment] 2020-06-04 18:37
Making other developers successful is what we live for. You're welcome and thank you and our entire community!

**Closed by justinfagnani** 2020-06-04 18:36 UTC
