### ISSUE TITLE
[docs] Polymer features that aren't in LitElement

### ISSUE THREAD

**Issue by rictic** [Polymer/lit-element#101] opened 2018-06-12 23:17 UTC
It looks like observers and computed functions are not supported (AIU https://github.com/Polymer/lit-element/issues/30#issuecomment-385568414), and instead you just do some logic in either didRender or _render, which is reasonable enough, but it'd be nice for it to be documented.

I started with the decorators linked here: https://github.com/Polymer/lit-element/issues/7#issuecomment-395878088 and their typings mention observer and computed.

**Comment by PaulHMason** [comment] 2018-06-14 05:40
Observers and computed functions aren't a feature of lit-element because they aren't required, so it doesn't really make sense to document that fact. The confusion stems from people comparing lit-element to a Polymer element, but they really aren't related and drawing comparisons will probably make things more confusing (especially to people who aren't familiar with Polymer).

**Comment by akc42** [comment] 2018-07-15 08:56
Yes, I just wasted a day chasing down the fact that camelcase propertied don't map to properties in the template with a "-" in them.  Event though this was a lit element sitting inside a polymer 3 template

https://github.com/Polymer/lit-element/issues/128

**Comment by ernsheong** [comment] 2018-11-22 00:58
`query` and `queryAll` decorators are also undocumented

**Comment by katejeffreys** [comment] 2018-12-13 03:46
Duplicate of https://github.com/Polymer/lit-element/issues/63

**Comment by katejeffreys** [comment] 2019-01-08 23:40
Duplicate of #63

**Closed** 2019-01-08 23:41 UTC
Labels: Area: docs
