### ISSUE TITLE
TypeError: Cannot read property 'nextSibling' of null

### ISSUE THREAD

**Issue by nokisnojok** [Polymer/lit-element#778] opened 2019-08-17 06:42 UTC
#### Live Demo

https://stackblitz.com/edit/lit-element-example-yqhp16?file=index.js

#### Steps to Reproduce
1. click button which innerHTML is 'click this to change data'. 

#### Expected Results
No error is throw

#### Actual Results
TypeError: Cannot read property 'nextSibling' of null

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

### Versions

- lit-element: v2.0.0-rc.2
- webcomponents: v2.2.3

**Comment by ernsheong** [comment] 2019-09-07 01:14
Possibly Related: https://github.com/Polymer/lit-html/issues/293

**Comment by justinfagnani** [comment] 2020-01-22 20:18
I think this is different from #293, which should be fixed at master now. It seems to have to do with overriding `createRenderRoot()`.

**Comment by sorvell** [comment] 2020-02-07 00:54
Confirmed that this is fixed on master via https://github.com/Polymer/lit-html/pull/966. This should be fixed with the next release of lit-html.

The reason it only happens when `createRenderRoot` is overridden is that in this case the `<t-b>` element's light DOM children are removed when the `<t-b>` element renders its lit-html template to its light DOM. 

Without the fix, an exception is caused when the containing `<t-a>` element updates and renders its lit-html template, specifically at the spot where it expects to update the light DOM children of `<t-b>` which are now removed. That exception prevents lit-html from committing any of the other template parts in `<t-a>`.

Testing with master this is fixed. The removed light DOM nodes in `<t-b>` are simply skipped and `<t-a>` updates as expected.

**Closed by sorvell** 2020-02-07 00:54 UTC
Labels: Severity: Critical
