### ISSUE TITLE
Attributes behave inconsistently between browsers

### ISSUE THREAD

**Issue by Tanbouz** [Polymer/lit-element#222] opened 2018-09-24 17:41 UTC
### Description
Inconsistent behaviour with attributes in Firefox (62) - MacOS 10.13.6. Atrribute value is passed to element's property in Firefox only if the attribute name is all lower case. 

Chrome & Safari on the other hand are wild. If your🐱wrote the custom element attribute as "somedaTa", and the element's inner property was named "soMeDaTa" it still works.

#37 +1 on how to name things to avoid ^ ... my attribute was simply camelCase per [this](https://github.com/Polymer/pwa-starter-kit/blob/21b8f8d1d3a7eac5a74e3807fee01ab65c18800d/index.html#L107)

#### Live Demo
Edit:
~~Unrelated: Default example doesn't work (great is not rendered)~~
~~https://stackblitz.com/edit/lit-element-example?file=index.js~~

Attempt to replicate using a Live Demo (demo broken #177 )
https://stackblitz.com/edit/lit-element-example-ddgblr

#### Steps to Reproduce
```
  "dependencies": {
    "@polymer/lit-element": "^0.6.1",
    "@webcomponents/webcomponentsjs": "^2.1.3"
  },
  "devDependencies": {
    "polymer-cli": "^1.8.0"
  }
```
my-app.js
```
import { LitElement, html } from "@polymer/lit-element";

class AnElement extends LitElement {
  static get properties() {
    return {
      // someData: { type: String },
      somedata: { type: String }
    };
  }

  render() {
    return html`
    <style> .s2 { color: red; } </style>
    <span class="s2">${this.somedata}</span>
    `;
  }
}

customElements.define("an-element", AnElement);

class MyElement extends LitElement {
  static get properties() {
    return {
      data: { type: String }
    };
  }

  constructor() {
    super();
    this.data = "apples";
  }

  render() {
    return html`
    <p>Test 1 someData<br><an-element someData="${this.data}"></an-element></p>
    <p>Test 2 somedata<br><an-element somedata="${this.data}"></an-element></p>
    <p>Test 3 SOMEDATA<br><an-element SOMEDATA="${this.data}"></an-element></p>
    <p>Test 4 sOmeDatA<br><an-element sOmeDatA="${this.data}"></an-element></p>
    `;
  }
}

customElements.define("my-element", MyElement);

```

index.html
```
<!doctype html>
<html lang="en">
  <head>
  </head>
  <body>
    <my-element></my-element>
    <script src="node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
    <script type="module" src="./my-app.js"></script>
  </body>
</html>
```
#### Expected Results
I'm not sure which is the intended behaviour.

#### Actual Results
Firefox ( guessing it might be related to @webcomponents/webcomponentsjs )
```
Test 1 someData

Test 2 somedata
apples
Test 3 SOMEDATA

Test 4 sOmeDatA

```

Chrome & Safari
```
Test 1 someData
apples
Test 2 somedata
apples
Test 3 SOMEDATA
apples
Test 4 sOmeDatA
apples
```

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v0.6.1
- webcomponents: v2.1.3

**Comment by sorvell** [comment] 2018-09-27 22:01
This is caused by https://github.com/webcomponents/custom-elements/issues/167.

**Comment by sorvell** [comment] 2018-12-10 18:55
Closing since this is a custom elements polyfill issue, as noted above.

**Closed by sorvell** 2018-12-10 18:55 UTC
