### ISSUE TITLE
there are so many unnecessary comment nodes generated by lit-element

### ISSUE THREAD

**Issue by zzzgit** [Polymer/lit-element#772] opened 2019-08-13 09:36 UTC
![Image of Yaktocat](https://i.imgur.com/SatncBc.png)

Why there are so many comment nodes generated by lit-element?

**Comment by web-padawan** [comment] 2019-08-13 11:18
Duplicate of #249 and explained there.

**Comment by hyperpress** [comment] 2019-08-13 14:51
Those aren't really for comments. lit-html uses those as placeholders. It
remembers where nodes for specific data are stored, and then only updates
the specific ones where data has changed so it doesn't have re-render the
entire dom.

**Comment by justinfagnani** [comment] 2019-08-13 15:15
The comment markers are how lit-html works. They're pretty fundamental and can't be fully removed.

**Closed by justinfagnani** 2019-08-13 15:15 UTC
