### ISSUE TITLE
Adding items to array does not trigger _render call

### ISSUE THREAD

**Issue by StefanGussner** [Polymer/lit-element#107] opened 2018-06-18 14:06 UTC
### Description

When changing array data the change is not recognized until `_requestRender()` is called

#### Live Demo
https://glitch.com/edit/#!/bold-cuticle

#### Steps to Reproduce
1. create my-element
2. create an array property
3. use the array property in the _render function
4. add items to the array in an event listener function

#### Expected Results
The _render function is called

#### Actual Results
Nothing happens

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ?] Edge
- [x] Safari 11
- [? ] Safari 10
- [ ?] IE 11

### Versions

- lit-element: v0.5.2
- webcomponents: vX.X.X

**Comment by Lodin** [comment] 2018-06-18 19:20
`lit-element` observes only properties defined in `static get properties()`. It does not provide any interface to observe mutation of an array or an object. Observing mutation is quite complex task and is out of scope of `lit-element`.

If you don't want to use `_requestRender()`, you can use immutable arrays and object, like I did in [this example](https://js-eqcpht.stackblitz.io).

**Comment by nicolasparada** [comment] 2018-06-18 19:36
This is the expected behavior. On Polymer they have [`this.set`](https://www.polymer-project.org/3.0/docs/devguide/model-data#set-path). On lit-element you can do:
```js
this.colors = [...this.colors, 'green']
```
To override the complete array instead of mutating it.

**Comment by StefanGussner** [comment] 2018-06-18 21:28
ok thx :)

**Comment by kr05** [comment] 2018-08-21 00:12
I currently have an array that receives updates from my db. After any updates, I manually call requestRender, which works fine...but would using the spread operator be more performant than calling requestRender? On a side not, it would be amazing if I could specifically tell lit-element (or the render method) what property or item changed from the array and only update that. Is that something that's currently possible? Thanks!

**Comment by sorvell** [comment] 2018-08-27 21:34
Out of the box, LitElement uses a strict equals check to see if a property has changed. This means it's ideally suited to immutable data patterns as noted [above](https://github.com/Polymer/lit-element/issues/107#issuecomment-398170214).

However, sometimes, you need more control over this, so LitElement 0.6 will be exposing a property-based invalidation function so you can decide exactly when and if setting a property should trigger an invalidation and rendering. For example, if a property is always an object that should only trigger rendering if a `key` property changes, you could do this:

```
static get properties() {
  foo: {shouldInvalidate: (value, oldValue) => value.key !== oldValue.key;}
}
```

To make any set to a mutating object/array typed property always trigger invalidation, you could do something like the following. Please note that for performance reasons you should use this pattern sparingly because it can sometimes can result in a large amount of unnecessary work.

```
static get properties() {
  foo: { shouldInvalidate: (value, oldValue) => true }
}
```

**Closed by sorvell** 2018-08-27 21:34 UTC

**Comment by TimPietrusky** [comment] 2018-09-28 15:53
@sorvell I can't seem to find a documentation for `shouldInvalidate`. Where should I look or is this just missing from the README?

**Comment by Westbrook** [comment] 2018-09-28 18:28
@TimPietrusky The API was going through active development at the time of the last post, you'll see the updated property name available in the README as `hasChanged`, and can be applied to your property as such: 
```
static get properties() {
  foo: { hasChanged: (value, oldValue) => true }
}
```

**Comment by aadamsx** [comment] 2018-09-29 00:05
From the README:
> React to changes: LitElement reacts to changes in properties and attributes by asynchronously rendering, ensuring changes are batched. This reduces overhead and maintains consistent state.

Just to be clear, this line should probabbly be changed to:

> LitElement ONLY reacts to changes in properties and attributes defined in ```static get properties()```.  It does this by asynchronously rendering, and ensuring changes are batched. This reduces overhead and maintains consistent state.

**Comment by aadamsx** [comment] 2018-09-29 23:07
@Westbrook, I see the Advanced update lifecycle note about hasChanged:

> If the property's hasChanged(value, oldValue) returns false, the element does not update. If it returns true, requestUpdate() is called to schedule an update.

When would you use something like this?
