### ISSUE TITLE
lit-element adding "<!---->" to bound text's

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/lit-element#843] opened 2019-10-25 11:57 UTC
If I 've code in a template like this:

                <h1 style="grid-area: header; width: 100%; height: 100%; align-self: auto;">
                    <t-t>${this.title}</t-t> <t-t>${this.title_extension}</t-t>
                </h1>

the resulting HTML looks like this:

                <h1 style="grid-area: header; width: 100%; height: 100%; align-self: auto;">
                    <t-t>Artikelstamm</t-t> <t-t></t-t>
                </h1>

why is the "" added? Is there a way I can stop this?

**Comment by lkraav** [comment] 2019-10-25 12:29
Please search "comments" first.

https://github.com/Polymer/lit-element/issues?q=is%3Aissue+comments+is%3Aclosed

Duplicate of #772 and others.

**Comment by jogibear9988** [comment] 2019-10-25 14:13
https://github.com/Polymer/lit-element/issues/249

**Comment by jogibear9988** [comment] 2019-10-25 14:15
I never saw this.

But problem is, can this somehow be stopped?
I have a component wich uses the InnerHTML for Translation and it contains the ""

**Comment by israelfloresdga** [comment] 2019-10-25 19:04
The comment here https://github.com/Polymer/lit-element/issues/772#issuecomment-520794142

**Comment by justinfagnani** [comment] 2019-10-25 22:11
This is fundamental to how lit-html works, and cannot change.

Instead of using `innerHTML`, try `textContent` or `innerText`.

**Closed by justinfagnani** 2019-10-25 22:11 UTC
