### ISSUE TITLE
Uncaught SyntaxError: Unexpected token p in JSON at position 0

### ISSUE THREAD

**Issue by alexlemaire** [Polymer/lit-element#752] opened 2019-07-24 13:59 UTC
Currently having an issue but I am not sure whether it is directly related to lit-element or to another component connected to it...

### Description
Error thrown when trying to pass an array or object from a parent component property to a child component via its attribute by using `childProperty="${ifDefined(JSON.stringify(this.parentProperty))}"` in the parent element's render function.

Error:
```
VM1373:1 Uncaught SyntaxError: Unexpected token p in JSON at position 0
    at JSON.parse (<anonymous>)
    at fromAttribute (updating-element.js?module:43)
    at Function._propertyValueFromAttribute (updating-element.js?module:236)
    at HTMLElement._attributeToProperty (updating-element.js?module:371)
    at HTMLElement.attributeChangedCallback (updating-element.js?module:326)
    at AttributeCommitter.commit (parts.js?module:79)
    at AttributePart.commit (parts.js?module:111)
    at TemplateInstance.update (template-instance.js?module:40)
    at NodePart.__commitTemplateResult (parts.js?module:245)
    at NodePart.commit (parts.js?module:186)
```

The code used to work (around 3 weeks ago I would say) and now I discovered the issue when trying to copy my work over for a new project. After having a look at the old project, I realized it was also affected (without code update).

It seems like for some reason, the object passed to the attribute is not the one I gave initially (found out by replacing the initial syntax with `.propertyName="${ifDefined(this.propertyToPass)}"`).

The new value given to the property is something like this:
```
part => {
  if (value === undefined && part instanceof AttributePart) {
    if (value !== part.value) {
      const name = part.committer.name;
      part.committer.element.removeAttribute(name);
   …
```

It appears that the error occurs also on first render when the properties aren't set yet.

#### Live Demo
[Here](https://stackblitz.com/edit/lit-element-bug)

**Note**: this was added after filling in the bug report. I noticed something that I commented after this initial comment.

#### Steps to Reproduce
1. Create `index.html`
2. Create `parent-element` which is your main component
3. Add `parentProperty` to the properties of `parent-element`
4. Append `parent-element` to the body of `index.html`
5. Create `child-element`
6. Add `childProperty` to the properties of `child-element`
7. Append `child-element` to `parent-element`
8. Give to the `childProperty` attribute the value "${ifDefined(JSON.stringify(this.parentProperty))}" through `parent-element`
9. Add a `script` tag to `index.html` in which you give to `parent-element`'s property `parentProperty` the value ["test", "test2", "test3"]

I assume this should do the trick.

#### Expected Results
No error thrown.

#### Actual Results
See description.

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
- lit-element: v2.2.0
Imported via "https://unpkg.com/lit-element@^2.1.0?module"

**Comment by alexlemaire** [comment] 2019-07-25 09:05
While creating the live demo I noticed that without using the *ifDefined* directive I ended up not having this issue in StackBlitz.

I reproduced again the bug the same way as I did in the live demo on my computer and it seems like it's working. So I suspect *ifDefined* to be the weak spot in that case...

**Comment by justinfagnani** [comment] 2019-09-05 22:07
I suspect the problem was duplicate version of the `lit-html` package, which would have cause the directive to not work. Closing as a duplicate of the duplicate package problem.

**Closed by justinfagnani** 2019-09-05 22:07 UTC
