### ISSUE TITLE
Using diplsay: -webkit-box

### ISSUE THREAD

**Issue by edoudou** [Polymer/lit-element#1036] opened 2020-07-20 12:13 UTC
## Description
I am trying to use `display : -webkit-box;` in a code, but it disappear when I do :
```
css `
... 
    display : -webkit-box;
...
```
I think it is tag as unsafe.

Is this behaviour normal ?

**Comment by sorvell** [comment] 2020-07-23 19:06
We don't transform the css at all so this may just be an issue with malformed css. We'd have to see more of the css to see. The basic usage you showed does work as is shown here:

https://stackblitz.com/edit/lit-element-demo-xrn7w9?file=src%2Fmy-element.js

Closing this is working as intended, but feel free to re-open it with more info if necessary.

**Closed by sorvell** 2020-07-23 19:06 UTC
Labels: Focus Area: Core Libraries
