### ISSUE TITLE
Manual operation DOM and Update properties Will cause inexplicable bugs

### ISSUE THREAD

**Issue by WUSO01** [Polymer/lit-element#1047] opened 2020-08-07 09:36 UTC
## Description

I created an [demo](https://codesandbox.io/s/lit-element-issues-t2hy2?file=/src/index.js)

I had an list `[0, 1, 2]`, rendered like

```html
<div>0</div>
<div>1</div>
<div>2</div>
```
Clickd the change Dom button will change the dom structure:
```html
<div>1</div>
<div>0</div>
<div>2</div>
```
I didn't update `list`, now click the 'done' button,update list `[0, 1, 2]` to `[1, 0, 2]`, but it's render:

```html
<div>0</div>
<div>1</div>
<div>2</div>
```
I console list print `[1, 0, 2]`, why list list is `[1, 0, 2]` but dom structure is `[0, 1, 2]`

**Comment by justinfagnani** [comment] 2020-08-07 17:09
You can't manually change the DOM under control of lit-html, you have to change the data then re-render. If you change the DOM you may disturb the marker nodes that lit-html uses to perform updates. In this case when you re-order the divs you also reorder the markers for the list items. The result is expected if you know how lit-html works, but clearly unexpected for most. So the best advice is don't do that. You can _give_ manually managed DOM to lit-html to render to a spot. We talk about this restriction a bit here: https://lit-element.polymer-project.org/guide/templates#design-a-performant-template

**Comment by justinfagnani** [comment] 2020-08-07 17:10
Closing as working as intended

**Closed by justinfagnani** 2020-08-07 17:10 UTC
Labels: Focus Area: Core Libraries
