### ISSUE TITLE
Slotted style for `li` elements being ignored

### ISSUE THREAD

**Issue by rgladwell** [Polymer/lit-element#756] opened 2019-07-29 16:15 UTC
When styling slotted `li` elements using the `::slotted(li)` selector, slotted styles appear to be ignored.

#### Live Demo

https://stackblitz.com/edit/lit-element-example-vlkjbm

#### Steps to Reproduce

1. Create `my-element` with slotted content and slotted styles that apply separately to `li` and `ul` elements.
2. Append `my-element` to document.body
3. Create `ul` with `li` elements.
4. Append `ul` to `my-element`

#### Expected Results

Slotted `li` style should apply.

#### Actual Results

Slotted `li` style is ignored.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [x] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

```sh
$ npm ls
list-element@0.0.1 /Users/ricardo/Projects/test-nested-slotted-lists-lit
├── @webcomponents/webcomponentsjs@2.2.10
└─┬ lit-element@2.2.1
  └── lit-html@1.1.1

$ npm --version
6.10.1
```

**Comment by web-padawan** [comment] 2019-07-30 09:45
According to the spec, `::slotted` only works for direct child nodes assigned to the slot.

So it works like that by design.

**Comment by rgladwell** [comment] 2019-07-30 09:46
Ah is there no way to style indirect child nodes?

**Comment by lkraav** [comment] 2019-07-30 10:39
> Ah is there no way to style indirect child nodes?

Only via global styles.

**Closed** 2019-07-30 11:15 UTC
