### ISSUE TITLE
lit-element + mobx legacy decorators

### ISSUE THREAD

**Issue by tamis-laan** [Polymer/lit-element#921] opened 2020-03-12 08:04 UTC
I'm trying to use lit-element together with mobx, for this i'm using webpack and bable. I'm using the folowing plugins for babel as described in the lit-element docs. 

```js
        plugins: [
          ['@babel/plugin-proposal-decorators',{decoratorsBeforeExport: true}],
          ['@babel/plugin-proposal-class-properties'],
        ]
```

The problem is that mobx requires legacy decorators and crashes when using @computed. However changing the above to:  

```js
        plugins: [
          ['@babel/plugin-proposal-decorators', {decoratorsBeforeExport: true, legacy:true}],
          ['@babel/plugin-proposal-class-properties', {legacy:true}],
        ]
```

Crashes babel with the error:
'decoratorsBeforeExport' can't be used with legacy decorators.

However removing 'decoratorsBeforeExport' breaks lit-element as property changes are no longer registered. 

Is there some way to make the two play nice together??

**Comment by justinfagnani** [comment] 2020-03-12 18:57
Thanks for the heads up. This is unfortunate. I think the Babel and TypeScript implementations of "legacy" decorators differ slightly. I think we can make it work by checking the arguments to the decorators more carefully.

I don't how this will fall on our priorities for the near term, so we'd definitely take contributions here.

**Comment by justinfagnani** [comment] 2020-03-12 19:04
Seems to be a dupe of #205 

I'm going to re-open #205 and close this one.

**Closed by justinfagnani** 2020-03-12 19:04 UTC
Labels: Severity: Low, Type: Enhancement, Why: Enable new use cases
