### ISSUE TITLE
requestUpdate get's triggered too often if extending and rendering via lit-html

### ISSUE THREAD

**Issue by daKmoR** [Polymer/lit-element#447] opened 2019-01-14 15:59 UTC
### Description
If you have a root app custom element which uses lit-html to render its content AND you extend 2 levels from LitElement (e.g. apply a mixin or have an in-between class) then `requestUpdate` will be triggered multiple times on init.

Just thinking out loud but there are two setters in `static createProperty` defined? If I debug both get executed on init
https://github.com/Polymer/lit-element/blob/master/src/lib/updating-element.ts#L283

#### Live Demo
https://stackblitz.com/edit/lit-element-request-update-bug?file=custom-greeting.js

#### Steps to Reproduce
1. MyBase extends LitElement
2. CustomGreeting extends MyBase
3. Render `my-greeting` via lit-html in `my-app` to body

#### Expected Results
requestUpdate get's executed ONE time on init

#### Actual Results
requestUpdate get's executed TWO times on init

### Browsers Affected
- [x] Chrome

### Versions
- lit-element: v2.0.0-rc.2

**Comment by kevinpschaaf** [comment] 2019-01-14 17:31
As far as I can tell, this is working as intended.

`requestUpdate` is called for just that -- to request an update; multiple requests are batched into only one actual `update`, which is run at microtask timing by default. `requestUpdate` will be called at a minimum once on connected, and once for every property assignment. So this method is designed to be very cheap and bail if an update has already been requested in a given turn.  Put another way, `requestUpdate` _is the mechanism_ by which batching occurs.

In your example, you have a default value assignment in the constructor (`this.name = 'World'`), you have a binding in the host element (`.name=${'some'}`), and the element is being connected, hence 3 requests to update.  This should not be affected by the number of subclasses/mixins applied.

Closing as WAI, please ping if I missed a nuance in your report.

**Closed by kevinpschaaf** 2019-01-14 17:31 UTC

**Comment by daKmoR** [comment] 2019-01-14 19:23
ahhh yeah that makes sense 🤔 
funny enough changing that behavior fixed a bug - but yeah maybe it's something unrelated 🙈 

definitely thx for the feedback 🤗 - tomorrow I'm gonna do another deep dive into our code to see what I can find - wish me luck 😆 🤣
