### ISSUE TITLE
UpdateComplete resolves before render ran at least once.

### ISSUE THREAD

**Issue by pkaske** [Polymer/lit-element#775] opened 2019-08-14 14:22 UTC
### Description
Is it by design that `updateComplete` resolves before `render` is called the first time?
I put together an example that should hopefully explain what I mean. I would expect `updateComplete` to resolve only after `render` was called at least once, hence it shouldn't resolve if `render` is never called because `shouldUpdate` hasn't returned true yet.

I'm I misunderstanding the purpose of `updateComplete` or is this a bug?

#### Live Demo
https://stackblitz.com/edit/lit-element-example-vfo8tt

#### Steps to Reproduce
In the demo
1. `updateComplete` in the `connectedCallback` resolves and injects some text in a dom element outside the wc to callback had run.
2. the timeout in `connectedCallback` triggers and updates `_show` to "unblock" `shouldRender`
3. the shadow root is rendered => shows text of wc.

#### Expected Results
I would have `updateComplete` expected to resolve after the timeout in `connectedCallback` allowed the wc to render. Technically there wasn't an update of the render root yet so it seems odd that `updateComplete` resolves.

This would result in:
1. shadow root is rendered => shows text of wc
2. then the innerHTML of the outside dom element get's updated in the cb of `updateComplete`

### Browsers Affected

- [x] Chrome
- [x] Firefox

Not tested:
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
- lit-element: v2.2.1
- webcomponents: v2.2.10

**Comment by CaptainCodeman** [comment] 2019-08-14 15:21
That seems kind of artificial - what are you actually trying to achieve / what's the use-case? There's the `firstUpdated` lifecycle method that may be better suited to what you need.

**Comment by pkaske** [comment] 2019-08-14 16:32
My situation is kinda complicated to describe so let me try to make a simplified example:

Imagine you have your own component called *parent-el* and inside it's sd there is a third party component called *list-loader*.

```html
<parent-el>
  #shadow-root
    <list-loader></list-loader>
</parent-el>
```
- `list-loader` has a method called *fetchList*. It fetches some list from a server.
- `parent-el` does some more prior configuration of `list-loader` like what sorting or what data fields to return for example. `parent-el` is basically a higher level abstraction for `list-loader`.
- To make `parent-el` easily usable for other components you add a public function called `loadMyData()`. So they just need to stamp `parent-el` anywhere and call `loadMyData()` at any time and `parent-el` takes care of the rest.

Now they start using `parent-el` like this:

```js
const list = document.createElement('parent-el');
document.querySelector('#someDiv').appendChild(list);
list.loadMyData();
```
What happens now is that `loadMyList` needs to set some config on `list-loader` and then call it's `fetchList` method. But for that to work `parentElement` has to wait till it's own render root has been stamped of course or `list-loader` wouldn't exist. 

My take now would be that `loadMyList` ensures that `list-loader` exists by waiting for `updateComplete` to resolve the first time.

```js
//...
loadMyList() {
  // I thought I could ensure list-loader was connected with updateComplete in case the dev calls it right after adding parent-el to the dom.
  this.updateComplete(async () => {
    const thridPartyList = this.shadowRoot.querySelector('list-loader');
    // Setup up some settings...
    const data = await thridPartyList.fetchList();
    // Do stuff with data.
  });
}
//...
```

But this doesn't work because it resolves before the first render call. `firstUpdated` is not an option because I don't necessarily know that the dev using `parent-el` want's to load the list right away. Also the dev may want to call `fetchMyList` later on to refresh the list. So it seems to be the easiest to make sure `fetchMyList` wait's for the render root to be ready if necessary.

Hope this makes sense. I'm happy to hear about better solutions if you think I'm missing something here.

Besides the use case it seems logical that `updateComplete` can only be resolved after at least one render occurred. Right now it feels to me like `updateComplete` gives a false signal in the first life circle run. Or I misunderstood it's purpose/definition and all I said is total crap :D
In that case I'm happy to get educated.

**Comment by pkaske** [comment] 2019-08-14 16:42
I'm aware that I can accomplish this by setting up my own promise in `firstUpdated` and waiting for this to resolve. But as said, it seem to me `updateComplete` should be the right thing to use here.

**Comment by blikblum** [comment] 2019-08-14 18:55
I'm using `updateComplete` [in connectedCallback](https://github.com/blikblum/nextbone-routing/blob/master/src/routerlink.js#L113) to wait for the first render and in my case i can't use `firstUpdated` because is a decorator.

I also expect this to just work.

**Comment by danleyb2** [comment] 2019-08-23 09:14
@pkaske 

I am not sure why `updateComplete` doesn't work for you,  i have always used it to wait for child components to resolve before using DOM apis like `querySelector` and it has always worked.

> My situation is kinda complicated to describe so let me try to make a simplified example:

i have tried to reproduce your simplified example and it seems to work okay but doesn't without  `updateComplete` wait
Live Demo : https://stackblitz.com/edit/lit-element-example-j2vdp5

hope it helps

**Comment by justinfagnani** [comment] 2019-09-05 20:02
@blikblum what do you mean "i can't use `firstUpdated` because is a decorator."?

**Comment by justinfagnani** [comment] 2019-09-05 21:59
Looking into this more, I think it would be a breaking change to change the behavior here. We at least have test code that assumes that the `updateComplete` promise will resolve if `requestUpdate()` is called. That seems like a fair assumption. If `shouldUpdate()` returns false and we change to not resolving `updateComplete`, then there would need to be another `requestUpdate()` (or other updating-enquing action) before `updateComplete` could resolve.

One way to think about `shouldUpdate()` is that it only controls whether the _work_ of `update()` should be done.

Another way is that it should mirror, `updated()`, which is understandable, but I'm afraid of back-compat here.

I added this to our list of potential breaking changes, but I'm going to close now as infeasible unfortunately.

**Closed by justinfagnani** 2019-09-05 21:59 UTC

**Comment by blikblum** [comment] 2019-09-06 00:02
> what do you mean "i can't use firstUpdated because is a decorator."?

When overriding `firstUpdated` in a decorator that extends the class, would require the final class consumer to call `super.firstUpdated` otherwise not needed

I was assuming that when overriding a method using a decorator this would be the super of the decorated class  method but after some test, this seems not be the case so the consumer is not required to call `firstUpdated`. I will update my code to use `firstUpdated`

Anyway, for the record, here's another case of mine that can not use `firstUpdated`: it [waits](https://github.com/blikblum/nextbone-routing/blob/master/src/router.js#L173) to an arbitrary element attached to a route before rendering the next one (a child element that is rendered inside an outlet element)

**Comment by manjukas** [comment] 2019-09-23 09:27
From what I understood, you are looking for hook that is called when the element and all it's children have been rendered?
I don't know if this is the correct thing to do.. what I do for similar situations is, I override firstUpdated, and use setTimeout to execute that code asynchronously. Initially I did find it strange firstUpdated being called before all children were rendered.
