### ISSUE TITLE
html` ${html`<something property=${object} />`} `

### ISSUE THREAD

**Issue by yorrd** [Polymer/lit-element#82] opened 2018-06-01 13:51 UTC
When nesting `html`` `-tags, properties get stringified, objects will appear as `[object Object]`

**Comment by jsilvermist** [comment] 2018-06-01 14:57
Instead of escaping the inner literal, try adding it as:
```js
html`Hello ${html`Meep`}!`;
```

**Comment by yorrd** [comment] 2018-06-03 19:51
@jsilvermist yes and when I use a function which wraps the html`` call within another one, any object property I use is stringified. If you can't reproduce it, let me know, I'll throw together a reproduction

**Comment by sorvell** [comment] 2018-06-08 19:31
This definitely unexpected, but we'll need to investigate. A reproduction would be helpful. Thanks!

**Comment by positlabs** [comment] 2018-06-10 17:46
Here's a repro: https://codepen.io/positlabs/pen/BVpEOj?editors=1000

Is there a recommended way of handling loops within the html template strings? I remember dom-repeat(?) in polymer, but I'd rather not use that.

**Comment by TimvdLippe** [comment] 2018-06-10 18:00
You should not call join to get a string, but just pass in the array
directly: https://codepen.io/anon/pen/OEWGKX?editors=1000

**Comment by sorvell** [comment] 2018-06-13 23:00
Here's an example demonstrating that the problem as initially described is working as intended: http://jsbin.com/yoqosif/edit?html,output.

It's unclear based on the latest discussion if there's an actual problem here so closing this issue. Please feel free to open a more specific issue if necessary. Thanks.

**Closed by sorvell** 2018-06-13 23:00 UTC
