### ISSUE TITLE
styles doesnt load if .select:before{content: '\hex' }

### ISSUE THREAD

**Issue by mnts** [Polymer/lit-element#858] opened 2019-12-03 05:51 UTC
so if I try to add content: html entity with \ symbol , style returns empty..

**Comment by web-padawan** [comment] 2019-12-03 07:14
Duplicate of #637.

As mentioned in that issue, you need to escape the backslash, e.g. `content:"\\2014"`

**Comment by kevinpschaaf** [comment] 2020-01-22 21:20
Closing as dup of #637 (which is still open to track fixing docs around the need to escape strings in JS).

**Closed by kevinpschaaf** 2020-01-22 21:20 UTC
