### ISSUE TITLE
recycle problem

### ISSUE THREAD

**Issue by hzmnet** [Polymer/lit-element#887] opened 2020-01-30 08:00 UTC
many times we want to catch an element or property need to waiting for firstUpdated()  and then continue to next step. 
it means Lit-element this framework will spend much time on waiting and useless render.

is there any way we don't need to render and then catch an element or property?

since the Polymer quick than Lit-element. when the `<main>` get the query propety changed it still on not Update state. 

```
<iron-location path="{{path}}" query="{{query}}" hash="{{hash}}"> </iron-location>
<main query="{{query}}"/>
```

**Comment by justinfagnani** [comment] 2020-01-30 15:30
I don't have enough to go on here. Where's the waiting? What do you mean by catch? Can you put a demo on Stackblitz?

**Comment by web-padawan** [comment] 2020-01-30 16:18
I guess author means microtask timing and `updateComplete` 🤔

**Comment by blikblum** [comment] 2020-01-30 19:38
Probably, he is requesting the same as https://github.com/Polymer/lit-element/issues/643

Currently i use `shouldUpdate` for such task which occurs before render but is still not ideal because is async and kind of misuses the API. Example: https://github.com/blikblum/lit-element-mobx-realworld-example-app/blob/master/src/pages/profile-page.js#L82-L98

**Comment by kevinpschaaf** [comment] 2020-02-27 19:48
Closing since we don't have a repro and are not sure how to proceed with helping.  If there is still an issue, please re-open with a clear reproduction case. Thanks.

**Closed by kevinpschaaf** 2020-02-27 19:48 UTC
Labels: More Info Needed
