### ISSUE TITLE
Updating second property from Promise prevents rendering the Promise result

### ISSUE THREAD

**Issue by SirkoS** [Polymer/lit-element#389] opened 2018-12-19 21:39 UTC
### Description
I use a promise to retrieve data for one property rendering it using the `until()` directive. Inside the callback I try to update another property. After the callback fired only the second property gets rendered, while the promise-based property is not rendered. 

If I drop the the assignment of the second property inside the callback, the promise-based property gets rendered again.

My tests only fails on Firefox (65). Chrome (73) does not seem affected. Currently I don't have the means to test other browsers.

*I'm not sure, if this is the right place to report this. If not, please move to whatever repo is.*

#### Live Demo

https://jsfiddle.net/sirko/t6wzsuLk/

#### Steps to Reproduce

1. assign a Promise to a property
2. inside the promise callback assign a value to a second property
3. after the Promise is resolved, only the second property gets rendered. the first one is left unchanged in the output.

#### Expected Results
Both properties' updated values are rendered after the Promise is resolved.

#### Actual Results
Only the property that did not use the Promise gets updated, while the Promise-based one's update is not rendered.

### Browsers Affected

- [ ] Chrome 73
- [x] Firefox 65
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
- lit-element: v0.6.5
- webcomponents: v2.2.1

**Comment by sorvell** [comment] 2018-12-19 22:44
Thanks for posting the issue. After investigation, this is actually the same as https://github.com/Polymer/lit-html/issues/708.

In the example returning ``` html`loading...` ``` is what makes `lit-html` see this as a new value. As a workaround until the issue is addressed, you can make your placeholder a static string, e.g. ``` `loading` ```.

Closing as a dup of https://github.com/Polymer/lit-html/issues/708.

**Closed by sorvell** 2018-12-19 22:44 UTC
Labels: Priority: Medium, Type: Bug
