### ISSUE TITLE
Passing variables into stylesheet via _render method results in comment 

### ISSUE THREAD

**Issue by ztzven** [Polymer/lit-element#66] opened 2018-05-17 02:36 UTC
Using https://stackblitz.com/edit/lit-element-example-zzo6gh as an example, inspect <span class="mood"> The color variable is a comment rather than the expected color.

Odd. Is `lit-element` broken? Or can you not use variables inside component stylesheets?

**Comment by ztzven** [comment] 2018-05-17 02:42
Also, in that example.. the output is `Web Components are red!` when really it logically should be `Web Components are bad!`

Is `lit-element` broken?

**Comment by TimvdLippe** [comment] 2018-05-18 11:15
This is a duplicate of https://github.com/Polymer/lit-html/issues/218 which has an open PR at https://github.com/Polymer/lit-html/pull/274

**Closed by TimvdLippe** 2018-05-18 11:15 UTC
